# Numpy

In [2]:
%pip install numpy
import numpy as np


Note: you may need to restart the kernel to use updated packages.


In [3]:
big_list = list(range(100000))
big_array = np.arange(100000)

In [4]:
%timeit [x ** 2 for x in big_list]

4.57 ms ± 100 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit big_array ** 2

45.5 μs ± 974 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### Creating arrays

In [6]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [9]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
a = np.array([0,0,0,0])
print(a)

[0 0 0 0]


In [11]:
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [14]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [15]:
print(np.eye(3)) #identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
rng = np.random.default_rng(seed=42)
print(rng.random((2,3)))

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [17]:
print(rng.integers(1,10,size=(3,3))) #uniform

[[7 7 7]
 [8 5 2]
 [8 5 5]]


In [18]:
print(rng.normal(loc=0, scale = 1,size = 5))

[ 0.77779194  0.0660307   1.12724121  0.46750934 -0.85929246]


### Array attributes and data types

In [19]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
print(m.ndim)

2


In [21]:
print(m.shape)

(2, 3)


In [22]:
print(m.size)

6


In [24]:
print(m.dtype)

int64


In [27]:
ints = np.array([1,2,3],dtype = np.int32)

In [28]:
ints.dtype

dtype('int32')

In [30]:
floats = np.array([1,2,3],dtype = np.float64)
floats.dtype
                  

dtype('float64')

### Indexing and Slicing

In [31]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
print(x[0])

10


In [33]:
print(x[5])

15


In [34]:
m = np.arange(1,13).reshape(3,4)
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
print(m[1,2])

7


In [36]:
print(m[1])

[5 6 7 8]


In [37]:
print(m[:,1])

[ 2  6 10]


### Vector operation

In [38]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

In [39]:
print(a,b)


[1 2 3 4] [10 20 30 40]


In [40]:
print(a+b)

[11 22 33 44]


In [42]:
print(a*b)

[ 10  40  90 160]


In [43]:
a = np.array([1,2,3])
b=10

In [44]:
print(a+b)

[11 12 13]


In [45]:
a = np.array([[1,2,3],
              [4,5,6]
             ])
a.shape
             

(2, 3)

In [46]:
b = np.array([10,20,30])
b.shape

(3,)

In [47]:
print(a+b)

[[11 22 33]
 [14 25 36]]


In [48]:
a = np.array([[1,2],
              [3,4]
             ])
a.shape

(2, 2)

In [49]:
b = np.array([10,20,30])
b.shape

(3,)

In [50]:
print(a+b) #addition not possible with that different matrix.

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 